### DISCUSSION TITLE
Use with two vue projects

### DISCUSSION THREAD

**Discussion by thedomeffm** [lhapaipai/symfony-vite-dev#72] [Show and tell]
_I love this bundle <3 thanks._

**I want to share how I configured the bundle to use it with the vue apps.**

## What I wanted

- My project uses symfony as REST API and a Vue App as UI and also a Vue App as Admin tasks.
- I do not want to scaffold the 3 sub-projects by hand
  - symfony cli for symfony and the npm commands provided by vue for.... vue

**The default documentation of the bundle creates all apps in the `assets` folder of symfony, which I dont like.**

## Project Structure

This is my desired structure:
```
my-cool-saas-project/
├── app/
│   ├── // ...
│   ├── package.json
│   └── vite.config.ts
├── api/
│   ├── // ...
│   └── composer.json
└── admin/
    ├── // ...
    ├── package.json
    └── vite.config.ts
```

## How to configure the symfony and the bundle

Install `pentatrion/vite-bundle`

1. add custom bundle config

_The `build_directory`'s are super weird, because they start at symfony's folder structure._

```yaml
# api/config/packages.yaml
pentatrion_vite:
    throw_on_missing_entry: true
    throw_on_missing_asset: true
    default_config: vite_config_app
    configs:
        vite_config_app:
            build_directory: '../../app/public/build-app'

        vite_config_admin:
            build_directory: '../../admin/public/build-admin'

```

```yaml
# api/config/routes/pentatrion_vite.yaml
when@dev:
    _pentatrion_vite_vite_config_app:
        path: /build-app/{path}
        defaults:
            _controller: Pentatrion\ViteBundle\Controller\ViteController::proxyBuild
            configName: vite_config_app
        requirements:
            path: ".+"

    _pentatrion_vite_vite_config_admin:
        path: /build-admin/{path}
        defaults:
            _controller: Pentatrion\ViteBundle\Controller\ViteController::proxyBuild
            configName: vite_config_admin
        requirements:
            path: ".+"

    _profiler_vite:
        path: /_profiler/vite
        defaults:
            _controller: Pentatrion\ViteBundle\Controller\ProfilerController::info

```

2. add controller endpoints for the app's redirects

_I want to render the base pages via twig (for better SEO) and the `/app` and `/admin` apps/routes are managed by vue._

```php
// api/src/Controller/AppController

final class AppController extends AbstractController
{
    #[Route('/app', name: 'app_redirect_main', stateless: true)]
    #[Route('/app/{subpage}', name: 'app_redirect_subpage', requirements: ['subpage' => '.+'], stateless: true)]
    public function app(): Response
    {
        return $this->render('app/index.html.twig');
    }

    #[Route('/admin', name: 'app_admin')]
    #[Route('/admin/{subpage}', name: 'app_admin_redirect_subpage', requirements: ['subpage' => '.+'], stateless: true)]
    public function admin(): Response
    {
        return $this->render('admin/index.html.twig');
    }
}
```

```twig
{% extends 'base.html.twig' %}

{% block title %}Admin{% endblock %}

{% block stylesheets %}
    {# or use 'vite_config_app' as third parameter for the app #}
    {{ vite_entry_link_tags('app', [], 'vite_config_admin') }}
{% endblock %}

{% block javascripts %}
    {# or use 'vite_config_app' as third parameter for the app #}
    {{ vite_entry_script_tags('app', [], 'vite_config_admin') }}
{% endblock %}

{% block body %}
    <div id="app">loading admin</div>
{% endblock %}

```

3. fix the vue apps to work

Install `vite-plugin-symfony`

```ts
// {admin|app}/vite.config.ts

// ...
import symfonyPlugin from 'vite-plugin-symfony';

export default defineConfig({
  base: '/build-admin/',
  build: {
    outDir: 'public/build-admin', // or 'public/build-app', for the app
    rollupOptions: {
      input: {
        app: './src/main.ts',
      }
    }
  },
  plugins: [
    vue(),
    vueDevTools(),
    symfonyPlugin(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    },
  },
})

```

```ts
// {api|admin}/src/router/index.js
const router = createRouter({
  // history: createWebHistory(import.meta.env.BASE_URL),
  history: createWebHistory('/admin'), // or '/app' when in app router
  // ...
}
```

## Result

- As I wanted now I can SEO optimized SSR pages on the landingpage `/`
- The saas can run on `/app`
- My admin ui can run on `/admin`

🎉 

> [!NOTE]
> I'll add a solution for the deployment when I am done with it :D
