### ISSUE TITLE
Multiple Vite config doesn't work

### ISSUE THREAD

**Issue by Webarkitekt** [lhapaipai/symfony-vite-dev#44]
### vite-plugin-symfony version

7.0.4

### vite-bundle version

7.0.4

### Description

When i try to use the multi config settings, it looks like it doesn't work, i get a Symfony error saying that my config doesn't exists. 

### How to reproduce

Here is my `pentatrion_vite.yaml` config :

```
pentatrion_vite:
    default_config: visitme
    builds:
        visitme:
            build_directory: visitme
        now:
            build_directory: now
```

### Possible Solution

If i dump `$bundleConfig` in src/DependencyInjection/PentatrionViteExtension.php `$bundleConfig['builds']` does contains my builds settings `$bundleConfig['configs']` is set but doesn't have any value, so this condition isn't true.

```
if (isset($bundleConfig['builds']) && !isset($bundleConfig['configs'])) {
    $bundleConfig['configs'] = $bundleConfig['builds'];
}
```

If i dump $bundleConfig['configs'] after the condition, it's empty

lines concerned : https://github.com/lhapaipai/symfony-vite-dev/blob/22afc712f8536360491133339a20930da3c02e38/src/vite-bundle/src/DependencyInjection/PentatrionViteExtension.php#L64
