### ISSUE TITLE
cant't use environment variables for default_config

### ISSUE THREAD

**Issue by MosiiAUT** [lhapaipai/symfony-vite-dev#62]
### vite-plugin-symfony version

6.5.3

### vite-bundle version

6.3.0

### your OS, node version, Symfony version, PHP version

Symfony 6.4, PHP 8.3

### Description

Currently you cant't use env-vars for the yaml config
I don't know exaclty when symfony resolves the value, but it must be at an later point.

If i delete these lines, everything works just fine.
https://github.com/lhapaipai/vite-bundle/blob/main/src/DependencyInjection/PentatrionViteExtension.php#L87-L89
At this point, the value of the `default_config` is "env_d1b4a019b4648045_VITE_DEFAULT_CONFIG_ef9103f96a58a62eea82a17dcf0bd8e1"

### How to reproduce

Create a config like this:

```yaml
pentatrion_vite:
    default_config: '%env(VITE_DEFAULT_CONFIG)%'
    throw_on_missing_entry: true
    configs:
        dev:
            build_directory: dist/debug
        prod:
            build_directory: dist/build
```

Try to set the environment variable in e.g. .env

### Possible Solution

I'd delete these three lines, as the devs should know what configs they are creating.
https://github.com/lhapaipai/vite-bundle/blob/main/src/DependencyInjection/PentatrionViteExtension.php#L87-L89
